import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("carta de aniversário gera PNG personalizado sem ano e funciona como visitante", async ({ page }, info) => {
  await page.route("**/api/**", (route) => route.fulfill({ status: 401, json: { message: "Entre na sua conta" } }));
  await page.goto("/people");
  await page.locator(".add-friend").click();
  await page.getByLabel("Nome", { exact: true }).fill("Marina Açucena");
  await page.getByLabel("Aniversário", { exact: true }).fill("1996-02-29");
  await page.getByRole("button", { name: "Salvar amigo" }).click();
  await page.getByRole("button", { name: /Marina Açucena/ }).click();
  await page.getByRole("button", { name: "Criar imagem de parabéns" }).click();
  await expect(page.getByRole("button", { name: "Baixar imagem de parabéns" })).toBeDisabled();
  await page.getByLabel("Mensagem", { exact: true }).fill("Que seu novo ciclo floresça!\nMuita alegria, saúde e boas colheitas. ♡");
  await page.getByLabel("Remetente", { exact: true }).fill("Carlos & família");
  const preview = page.locator(".birthday-card-preview img");
  await expect(preview).toBeVisible();
  await expect(preview).toHaveAttribute("alt", /Marina Açucena, 29 de fevereiro/);
  await expect(preview).not.toHaveAttribute("alt", /1996/);
  await expect(preview).toHaveAttribute("alt", /Carlos & família/);
  await expect(page.getByRole("button", { name: "Baixar imagem de parabéns" })).toBeEnabled();
  const source = await preview.getAttribute("src");
  const downloadEvent = page.waitForEvent("download");
  await page.getByRole("button", { name: "Baixar imagem de parabéns" }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe("parabens-marina-acucena.png");
  const path = await download.path();
  const bytes = await readFile(path!);
  expect(bytes.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  expect(bytes.readUInt32BE(16)).toBe(1080);
  expect(bytes.readUInt32BE(20)).toBeGreaterThanOrEqual(1440);
  expect(bytes.toString("base64")).toBe(source!.split(",")[1]);
  await download.saveAs("test-results/birthday-card-" + info.project.name + ".png");
  await page.screenshot({ path: "test-results/birthday-editor-" + info.project.name + ".png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel("Mensagem", { exact: true }).fill(Array(26).fill("Uma linha").join("\n"));
  await expect(page.getByRole("alert")).toContainText("muitas linhas");
  await expect(page.getByRole("button", { name: "Baixar imagem de parabéns" })).toBeDisabled();
  await page.getByRole("button", { name: "Voltar à pessoa" }).click();
  await expect(page.getByRole("button", { name: "Criar imagem de parabéns" })).toBeVisible();
});
